apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: webhook
  ports:
    - protocol: TCP
      port: {{ .Values.webhook.port }}
      targetPort: {{ .Values.webhook.port }}
  type: ClusterIP

